# Generated by Django 4.1.3 on 2022-12-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'verbose_name': 'Континент', 'verbose_name_plural': 'Континенты'},
        ),
    ]
